Models/Data/Item.cs
namespace WebInventoryManagement.Models.Data
{
    public class Item
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public Shelf Shelf { get; set; }
        public Category Category { get; set; }
        public int ShelfId { get; set; }
        public int CategoryId { get; set; }

        public Store Store { get; set; }

        public int StoreId { get; set; } 


        public Item(int id, string itemName, int price, int quantity, string description, Shelf shelf, Category category)
        {
            Id = id;
            ItemName = itemName;
            Price = price;
            Quantity = quantity;
            Description = description;
            Shelf = shelf;
            Category = category;

            StoreId = shelf?.Store?.Id ?? 0;
            Store = shelf.Store;

            ShelfId = shelf?.Id ?? 0;
            CategoryId = category?.Id ?? 0;
        }

        public Item() { }
    }
}

Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.Design;
using WebInventoryManagement.Models.Data;
using WebInventoryManagement.Services;

namespace WebInventoryManagement.Controllers
{
    public class ItemController : Controller
    {
        private readonly ILogger<HomeController>? _logger;

        private ItemService itemService;

        private ShelfService shelfService;

        private CategoryService categoryService;

        private StoreService storeService;



        public ItemController(ItemService itemService, ShelfService shelfService, CategoryService categoryService, StoreService storeService)
        {
            this.itemService = itemService;
            this.shelfService = shelfService;
            this.categoryService = categoryService;
            this.storeService = storeService;
        }

        public IActionResult Index()
        {
            IEnumerable<Item> items = itemService.GetAll();
            LoadViewBagShelvesList();
            LoadViewBagStoresList();
            return View(items);
        }


        [HttpGet]
        public ActionResult Create()
        {
            // Получите список категорий из вашего сервиса или базы данных
            LoadViewBagShelvesList();
            LoadViewBagCategoriesList();

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item item)
        {

            if (item.ItemName != null)
            {
                item.Shelf = (from shelf in shelfService.GetAll() where shelf.Id == item.ShelfId select shelf).First();
                item.Category = (from category in categoryService.GetAll() where category.Id == item.CategoryId select category).First();

                itemService.Save(item);
                return RedirectToAction("Index");// Перенаправить на экшен Index
            }


            LoadViewBagCategoriesList();
            LoadViewBagShelvesList();

            return View();

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var item = itemService.GetById(id);

            if (item == null)
            {
                return NotFound();
            }

            itemService.Delete(item);

            return RedirectToAction("Index");

        }

        public IActionResult Edit(int id)
        {
            var shelf = itemService.GetById(id);
            if (shelf == null)
            {
                return NotFound();
            }
            LoadViewBagCategoriesList();
            LoadViewBagShelvesList();

            return View("Edit", shelf);
        }

        [HttpPost]
        public IActionResult Update(Item item)
        {
            if (item.ItemName != null)
            {
                item.Shelf = (from shelf in shelfService.GetAll() where shelf.Id == item.ShelfId select shelf).First();
                item.Category = (from category in categoryService.GetAll() where category.Id == item.CategoryId select category).First();


                itemService.UpdateItem(item);
                return RedirectToAction("Index");
            }
            return View("Edit", item);
        }

        private void LoadViewBagShelvesList()
        {
            ViewBag.ShelfList = ViewBagLoader.LoadViewBagList(shelfService.GetAll(), "Id", "ShelfName");

        }

        private void LoadViewBagCategoriesList()
        {
            ViewBag.CategoryList = ViewBagLoader.LoadViewBagList(categoryService.GetAll(), "Id", "CategoryName");
        }

        private void LoadViewBagStoresList()
        {
            ViewBag.StoreList = ViewBagLoader.LoadViewBagList(storeService.GetAll(), "Id", "StoreName");
        }

    }
}

Views/Item/Create.cshtml
@model WebInventoryManagement.Models.Data.Item
@{
    ViewData["Title"] = "Create Item";
}

<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.ItemName, htmlAttributes:
            new{ @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.ItemName, new{ htmlAttributes =
                new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.ItemName, "",
                new{ @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes:
            new{ @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new{ htmlAttributes =
                new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.Description, "",
                new{ @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => Model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => Model.CategoryId, new SelectList(ViewBag.CategoryList, "Value", "Text"))
                    @Html.ValidationMessageFor(model => Model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => Model.ShelfId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => Model.ShelfId, new SelectList(ViewBag.ShelfList, "Value", "Text"))
                    @Html.ValidationMessageFor(model => Model.ShelfId, "", new { @class = "text-danger" })
                </div>
            </div>






            <div class="form-group" style="display:inherit">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary"  />
                </div>
                <div class="col-md-offset-2 col-md-10" >
                    @Html.ActionLink("Back to List", "Index") 
                </div>
            </div>
        </div>
    }


</div>

Views/Item/Edit.cshtml
@model WebInventoryManagement.Models.Data.Item
@{
    ViewData["Title"] = "Edit Item";
}

<body>
    @using (Html.BeginForm("Update", "Item", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">

                <div class="col-md-10" style="display: none;">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ItemName, htmlAttributes:
            new{ @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.ItemName, new{ htmlAttributes =
                new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.ItemName, "",
                new{ @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes:
            new{ @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new{ htmlAttributes =
                new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.Description, "",
                new{ @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => Model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => Model.CategoryId, new SelectList(ViewBag.CategoryList, "Value", "Text"))
                    @Html.ValidationMessageFor(model => Model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => Model.ShelfId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => Model.ShelfId, new SelectList(ViewBag.ShelfList, "Value", "Text"))
                    @Html.ValidationMessageFor(model => Model.ShelfId, "", new { @class = "text-danger" })
                </div>
            </div>






            <div class="form-group" style="display:inherit">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default" style="text-decoration: underline; color: blue; cursor: pointer;" />
                </div>
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    }
</body>

Views/Item/Index.cshtml
@using WebInventoryManagement.Models.Data;
@{
    ViewData["Title"] = "Items";
}
<body>
    <div class="container mt-3">

        <div class="d-flex justify-content-between align-items-center mb-3">

            <a href="/Item/Create" class="btn btn-primary">Add Item</a>
            <div style="width: 10%;"></div>

            <div>
                <label for="storeComboBox">Select Store:</label>
                <select id="storeComboBox" onchange="filterItems()">
                    <option value="All">All</option>
                    @foreach (var store in ViewBag.StoreList)
                    {
                        <option value="@store.Value">@store.Text</option>
                    }
                </select>
            </div>

            <div>
                <label for="shelfComboBox">Select Shelf:</label>
                <select id="shelfComboBox" onchange="filterItems()">
                    <option value="All">All</option>
                    @foreach (var shelf in ViewBag.ShelfList)
                    {
                        <option value="@shelf.Value.ToLower()">@shelf.Text</option>
                    }
                </select>
            </div>




        </div>

        <input type="text" id="searchBox" placeholder="Search by name..." onkeyup="filterItems()">


        <table class="table">
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Description</th>

                    <th>Category</th>
                    <th>Shelf</th>
                    <th>Actions</th>



                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="item-row" data-shelf-id="@item.Shelf.Id" data-store-id="@item.StoreId">
                        <td>@item.ItemName</td>
                        <td>@item.Price</td>
                        <td>@item.Quantity</td>
                        <td>@item.Description</td>
                        <td>@item.Category.CategoryName</td>
                        <td>@item.Shelf?.ShelfName</td>
                        <td>
                            <form asp-controller="Item" asp-action="Edit" asp-route-id="@item.Id" method="post">
                                <button class="btn-primary">Edit</button>
                            </form>
                            <form asp-controller="Item" asp-action="Delete" asp-route-id="@item.Id" method="post" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                <button class="btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>

                }
            </tbody>



        </table>
    </div>

    <script>
        function filterItems() {
            var selectedStoreId = $('#storeComboBox').val();
            var selectedShelfId = $('#shelfComboBox').val();

            var searchText = $('#searchBox').val().toLowerCase();

            $('.item-row').each(function () {
                var storeId = $(this).data('store-id').toString();
                var shelfId = $(this).data('shelf-id').toString();
                var itemName = $(this).find('td:first').text().toLowerCase();

                var storeMatch = (selectedStoreId === 'All' || storeId === selectedStoreId);
                var shelfMatch = (selectedShelfId ==='All' || shelfId === selectedShelfId);
                var nameMatch = itemName.startsWith(searchText);

                if (shelfMatch && storeMatch && nameMatch) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
        }







    </script>

</body>