Models/Data/Store.cs
namespace WebInventoryManagement.Models.Data
{
    public class Store
    {
        public int Id { get; set; }
        public string StoreName { get; set; }
        public int ShelfCount { get; set; } = 0;



        public Store(int id, string storeName, int shelfCount)
        {
            Id = id;
            StoreName = storeName;
            ShelfCount = shelfCount;
        }

        public Store()
        {
        }
    }
}

Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using WebInventoryManagement.Models;
using WebInventoryManagement.Models.Data;
using WebInventoryManagement.Services;

namespace WebInventoryManagement.Controllers
{
    public class StoreController : Controller
    {
        StoreService storeService;

        public StoreController(StoreService _storeService)
        {
            this.storeService = _storeService;
        }

        private readonly ILogger<HomeController> _logger;



        public ActionResult Index()
        {
            IEnumerable<Store> stores = storeService.GetAll();
            return View(stores);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Store store)
        {
            if (ModelState.IsValid)
            {
                storeService.Save(store);
                return RedirectToAction("Index"); // Перенаправить на экшен Index
            }
            return View(); // В случае ошибки возвращаем ту же форму для исправления
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                var store = storeService.GetById(id);

                if (store == null)
                {
                    return NotFound();
                }

                storeService.Delete(store);
                return RedirectToAction("Index");
            }
            catch (Exception ex) 
            {
                if (ex.Message.Contains("ORA-02292"))
                {
                    return RedirectToAction("Error", new { message = "The Store cannot be deleted because there are Shelf entries associated with it." });
                }
                throw;
            }
        }


        public IActionResult Edit(int id)
        {
            var store = storeService.GetById(id);
            if (store == null)
            {
                return NotFound(); // Handle the case where the store is not found.
            }
            return View("Edit", store);
        }

        [HttpPost]
        public IActionResult Update(Store store)
        {
            if (ModelState.IsValid && store.StoreName != "" && store.StoreName!=null)
            {
                storeService.Update(store);
                return RedirectToAction("Index");
            }
            return View("Edit", store);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("[controller]/Error")]
        public ActionResult Error(int? statusCode, string message = null)
        {
            return ErrorHandler.Error(this, statusCode, message);
        }







    }
}

Views/Store/Create.cshtml
@model WebInventoryManagement.Models.Data.Store
@{
    ViewData["Title"] = "Create Store";
}

<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.StoreName, htmlAttributes:
            new{ @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.StoreName, new{ htmlAttributes =
                new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.StoreName, "",
                new{ @class = "text-danger" })
                </div>
            </div>


            <div class="form-group" style="display:inherit">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary"  />
                </div>

                <div>
                    @Html.ActionLink("Back to List", "Index")

                </div>


            </div>



        </div>
    }



</body>

Views/Store/Edit.cshtml
@model WebInventoryManagement.Models.Data.Store
@{
    ViewData["Title"] = "Edit Store";
}

<body>
    @using (Html.BeginForm("Update", "Store", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.StoreName, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.StoreName, new { htmlAttributes = new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.StoreName, "", new { @class = "text-danger" })
                </div>
            </div>

           

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default" style="text-decoration: underline; color: blue; cursor: pointer;" />
                </div>
            </div>
        </div>
    }
</body>

Views/Store/Index.cshtml
@{
    ViewData["Title"] = "Stores";
}

<div>
    <a href="/Store/Create" class="btn btn-primary">Add Store</a>


    <table class="table">
        <thead>
            <tr>
                <th>Store Name</th>
                <th>Shelf Count</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var store in Model)
            {
                <tr>
                    <td>@store.StoreName</td>
                    <td>@store.ShelfCount</td>
                    <td>
                        <form asp-controller="Store" asp-action="Edit" asp-route-id="@store.Id" method="post">
                            <button class="btn-primary" type="submit" >Edit</button>
                        </form>
                        <form asp-controller="Store" asp-action="Delete" asp-route-id="@store.Id" method="post" onsubmit="return confirm('Are you sure you want to delete this store?');">
                            <button class="btn-danger" type="submit">Delete</button>
                        </form>

                    </td>
                </tr>
            }
        </tbody>
    </table>




</div>