Models/Data/Shelf.cs
namespace WebInventoryManagement.Models.Data
{
    public class Shelf
    {
        public int Id { get; set; }
        public string ShelfName { get; set; }
        public int ItemCount { get; set; }
        public Category Category { get; set; }

        public Store Store { get; set; }

        public int StoreId { get; set; }

        public int CategoryId { get; set; }
        public Shelf(int id, string shelfName, int itemCount, Category category, Store store)
        {
            Id = id;
            ShelfName = shelfName;
            ItemCount = itemCount;
            Category = category;
            Store = store;


            StoreId = store.Id;
            CategoryId = category.Id;
        }
        public Shelf() { }
    }
}

Controllers/ShelfController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebInventoryManagement.Models.Data;
using WebInventoryManagement.Services;

namespace WebInventoryManagement.Controllers
{
    public class ShelfController : Controller
    {
        private ShelfService shelfService;

        private StoreService storeService;

        private CategoryService categoryService;

        private readonly ILogger<HomeController> _logger;

        //public ShelfController(ShelfService _shelfService)
        //{
        //    this.shelfService = _shelfService;
        //}

        public ShelfController(ShelfService shelfService, StoreService storeService, CategoryService categoryService)
        {
            this.shelfService = shelfService;
            this.storeService = storeService;
            this.categoryService = categoryService;
        }

        public ActionResult Index()
        {
            IEnumerable<Shelf> shelves = shelfService.GetAll();
            LoadViewBagStoresList();

            return View(shelves);
        }

        [HttpGet]
        public ActionResult Create()
        {
            // Получите список категорий из вашего сервиса или базы данных
            LoadViewBagCategoriesList();
            LoadViewBagStoresList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Shelf shelf)
        {

            if (shelf.ShelfName != null)
            {
                shelf.Store = (from store in storeService.GetAll() where store.Id == shelf.StoreId select store).First();
                shelf.Category = (from category in categoryService.GetAll() where category.Id == shelf.CategoryId select category).First();

                shelfService.Save(shelf);
                return RedirectToAction("Index");// Перенаправить на экшен Index
            }

            LoadViewBagCategoriesList();
            LoadViewBagStoresList();

            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {


            try
            {
                var shelf = shelfService.GetById(id);

                if (shelf == null)
                {
                    return NotFound();
                }

                shelfService.Delete(shelf);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                if (ex.Message.Contains("ORA-02292"))
                {

                    return RedirectToAction("Error", new { message = "The Shelf cannot be deleted because there are Item entries associated with it." });
                }
                throw;
            }

        }


        public IActionResult Edit(int id)
        {
            var shelf = shelfService.GetById(id);
            if (shelf == null)
            {
                return NotFound();
            }
            LoadViewBagCategoriesList();
            LoadViewBagStoresList();

            return View("Edit", shelf);
        }
        [HttpPost]
        public IActionResult Update(Shelf shelf)
        {
            if (shelf.ShelfName != null)
            {
                shelf.Store = (from store in storeService.GetAll() where store.Id == shelf.StoreId select store).First();
                shelf.Category = (from category in categoryService.GetAll() where category.Id == shelf.CategoryId select category).First();


                shelfService.Update(shelf);
                return RedirectToAction("Index");
            }
            return View("Edit", shelf);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("[controller]/Error")]
        public ActionResult Error(int? statusCode, string message = null)
        {
            return ErrorHandler.Error(this, statusCode, message);
        }



        private void LoadViewBagStoresList()
        {
            ViewBag.StoreList = ViewBagLoader.LoadViewBagList(storeService.GetAll(), "Id", "StoreName");
        }
        private void LoadViewBagCategoriesList()
        {
            ViewBag.CategoryList = ViewBagLoader.LoadViewBagList(categoryService.GetAll(), "Id", "CategoryName");
        }


    }
}

Views/Shelf/Create.cshtml
@model WebInventoryManagement.Models.Data.Shelf
@{
    ViewData["Title"] = "Create Shelf";
}

<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.ShelfName, htmlAttributes:
            new{ @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.ShelfName, new{ htmlAttributes =
                new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.ShelfName, "",
                new{ @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => Model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => Model.CategoryId, new SelectList(ViewBag.CategoryList, "Value", "Text"))
                    @Html.ValidationMessageFor(model => Model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => Model.StoreId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => Model.StoreId, new SelectList(ViewBag.StoreList, "Value", "Text"))
                    @Html.ValidationMessageFor(model => Model.StoreId, "", new { @class = "text-danger" })
                </div>
            </div>






            <div class="form-group" style="display:inherit">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary"  />
                </div>
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    }


</div>

Views/Shelf/Edit.cshtml
@model WebInventoryManagement.Models.Data.Shelf
@{
    ViewData["Title"] = "Edit Shelf";
}

<body>
    @using (Html.BeginForm("Update", "Shelf", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">

                <div class="col-md-10" style="display: none;">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ShelfName, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    @Html.EditorFor(model => model.ShelfName, new { htmlAttributes = new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.ShelfName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => Model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => Model.CategoryId, new SelectList(ViewBag.CategoryList, "Value", "Text"))
                    @Html.ValidationMessageFor(model => Model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => Model.StoreId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => Model.StoreId, new SelectList(ViewBag.StoreList, "Value", "Text"))
                    @Html.ValidationMessageFor(model => Model.StoreId, "", new { @class = "text-danger" })
                </div>
            </div>






            <div class="form-group" style="display:inherit">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default" style="text-decoration: underline; color: blue; cursor: pointer;" />
                </div>
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    }
</body>

Views/Shelf/Index.cshtml
@using WebInventoryManagement.Models.Data;
@{
    ViewData["Title"] = "Shelves";
}

<body>
    <div class="container mt-3">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <a href="/Shelf/Create" class="btn btn-primary">Add Shelf</a>
            <div style="width: 10%;"></div>
            <div>
                <label for="storeComboBox">Select Store:</label>
                <select id="storeComboBox" onchange="filterShelves()">
                    <option value="All">All</option>
                    @foreach (var store in ViewBag.StoreList)
                    {
                        <option value="@store.Value">@store.Text</option>
                    }
                </select>
            </div>
        </div>

        <input type="text" id="searchBox" placeholder="Search by name..." onkeyup="filterShelves()">

        <table class="table">
            <thead>
                <tr>
                    <th>Shelf Name</th>
                    <th>Items count</th>
                    <th>Category</th>
                    <th>Store</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var shelf in Model)
                {
                    <tr class="item-row" data-store-id="@shelf.Store.Id">
                        <td>@shelf.ShelfName</td>
                        <td>@shelf.ItemCount</td>
                        <td>@shelf.Category.CategoryName</td>
                        <td>@shelf.Store.StoreName</td>
                        <td>
                            <!-- Action Buttons -->
                            <form asp-controller="Shelf" asp-action="Edit" asp-route-id="@shelf.Id" method="post">
                                <button class="btn-primary" type="submit" class="btn-link">Edit</button>
                            </form>
                            <form asp-controller="Shelf" asp-action="Delete" asp-route-id="@shelf.Id" method="post" onsubmit="return confirm('Are you sure you want to delete this shelf?');">
                                <button class="btn-danger" type="submit" class="btn-link">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <script>
        function filterShelves() {
            var selectedStoreId = $('#storeComboBox').val();
            var searchText = $('#searchBox').val().toLowerCase();

            $('.item-row').each(function () {
                var storeId = $(this).data('store-id').toString();
                var shelfName = $(this).find('td:first').text().toLowerCase();

                var storeMatch = (selectedStoreId === 'All' || storeId === selectedStoreId);
                var nameMatch = shelfName.startsWith(searchText);

                if (storeMatch && nameMatch) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
        }


    </script>

</body>